server:
  port: 8090

spring:
  datasource:
    storage-platform:
      jdbc-url: jdbc:mysql://localhost:3306/storage_platform?rewriteBatchedStatements=true&useUnicode=true&serverTimezone=Asia/Shanghai&autoReconnect=true&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
      username: root
      password: 123456
      driver-class-name: com.mysql.cj.jdbc.Driver
      maximum-pool-size: 20
      idle-timeout: 30000
      connection-test-query: SELECT 1